### ISSUE TITLE
Do not mention deleting old versions of Paperback

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/website#100]
The Testflight guides both mention deleting any other installed version of Paperback before installing the new one. However, this is not always necessary, especially if a Public Testflight user is upgrading to a Patreon Testflight account. I think mentioning that Public Testflight users can normally upgrade to the Patreon version would help.

**Comment by Celarye** [comment]
This is not supported with the current versions of Paperback.
