### ISSUE TITLE
Extension development page still mentions extensions-promises

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/website#101]
https://github.com/Paperback-iOS/website/blob/61d74d2f3b073834d64b06ad5cb0243416fc9ad1/src/help/contribution/extension-development/quickstart.md?plain=1#L10

**Comment by Celarye** [comment]
The Vuepress website is getting replaced with a Vitepress one, we'll make sure all info on there is up to date.

**Comment by Celarye** [comment]
Fixed with the Vitepress website
