### ISSUE TITLE
Unread counter goes up every time I open a manga

### ISSUE THREAD

**Issue by Battler624** [Paperback-iOS/website#120]

**Comment by Battler624** [comment]
https://user-images.githubusercontent.com/9511158/171111757-6d10ab00-5279-4a69-aa73-801149162955.MOV

Example here, sorry I'm on mobile atm, no formatting

**Comment by Celarye** [comment]
This is the website its repository, consider opening an issue in the [app repository](https://github.com/Paperback-iOS/app) if you're still experiencing this issue.
