### ISSUE TITLE
[New feature] Possibility to add more filters

### ISSUE THREAD

**Issue by Bencyril** [Paperback-iOS/website#124]
Hi guys!

After using the app, that is really nice, I think it's missing one thing:
 - Grouping multiple Filters in one search

Currently, the only possible way to filter is only by Genre (Action, Adventure, Shōnen, others)
And you have to check each repo to find the status like running, completed or other

Would be nice to have in the search the possibility to filter by Genre AND by Status 

Thanks !

**Comment by FaizanDurrani** [comment]
This is already possible, ask extension developers to adopt it.
Also, not the correct place to post app feature requests, they go to https://github.com/paperback-ios/app
