### ISSUE TITLE
Additional help for organizing bookmarks

### ISSUE THREAD

**Issue by ocreturner** [Paperback-iOS/website#126]
I tend to add bookmarks to the main library and not to sections. Then from the main library I create sections and I add them to there. 

Is there a way to add a sort by sites or at least an icon to show if a manhwa was already sent to a category already? 

It's tough to move bookmarks to categories without accidentally adding to 2 or more bookmarks to different categories. 

Tldr: add a way to show an emblem or emoji to bookmarks to easily organize bookmarks without the user accidentally  forgetting that it's already in another category

**Comment by rintendou** [comment]
Hi there! You've created a request in the wrong repository, this is one is for the Paperback website, not the app.

**Comment by Obadiahcruz** [comment]
Whoops sorry about that thanks
