### ISSUE TITLE
Cannot add Komga to Paperback

### ISSUE THREAD

**Issue by chemicalsam** [Paperback-iOS/website#131]
![6A008AEE-5D05-466F-9E29-0029A10473F9](https://user-images.githubusercontent.com/67978865/205371705-d88e2dd9-cdba-4078-8fff-19588789c7d0.png)
I followed the instructions by adding my URL, username and password to Paperback and I get this error when trying to reload the app.

**Comment by SheepYY039** [comment]
This also happens to me. I have tried reinstalling the application multiple times and still couldn't find the origin of this issue.

**Comment by SheepYY039** [comment]
@chemicalsam btw, what application are you using to read from komga after you experienced this issue? I can only use my browser to read, but I prefer reading from an app.

**Comment by Celarye** [comment]
This is the website its repository, consider opening an issue in the [app repository](https://github.com/Paperback-iOS/app) if you're still experiencing this issue.
