### ISSUE TITLE
Website update project

### ISSUE THREAD

**Issue by FramboisePi** [Paperback-iOS/website#47]
# Website update

### FAQ
* reader settings:
    * disable tap to advance
    * mask the top and bottom bar by pressing in the center of the reader
* Extensions
    * Using a self-hosted source 

### User guides
* merging titles
* migrating the library
* using trackers

### Contributing guide
* Update for the latest extensions-common versions
* Dynamic UI guide

---

This issue list things that should/could be done to improve the website. The idea is to regroup them somewhere to keep track of what is done and what need to be worked on.
**Contributions are really welcome.**

**Comment by Celarye** [comment]
@Akiawa the following guides should be added to the VitePress website as well:
> - reader settings:
> - merging titles
> - migrating the library

**Comment by Akiawa** [comment]
Will do when possible!

**Comment by Celarye** [comment]
Implemented in the Vitepress website
